# Setup
title:        "{...jsbw}"
description:  "The blog about everything Javascript!"
tagline:      Javascript...but why?
baseurl:      ""
paginate:     1
include:      ["_pages"]
permalink:    /:title/

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# About/contact
author:
  name:       José Del Valle
  url:        http://dlvx.github.io/about

#Others
markdown: kramdown
sass:
  style: compressed

