# Setup
title:        "{...jsbw}"
description:  "Javascript Blog"
tagline:      José Del Valle #Javascript...but why?
baseurl:      ""
paginate:     1
include:      ["_pages"]
permalink:    /:title/

# About/contact
author:
  name:       José Del Valle
  url:        http://dlvx.github.io/about

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-seo-tag