# Setup
title:        JSBW
tagline:      Javascript...but why?
baseurl:      ""
paginate:     1
include:      ["_pages"]
permalink:    /:title/

# About/contact
author:
  name:       José Del Valle
  url:        http://dlvx.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
sass:
  style: compressed