# Setup
title:        José Del Valle
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
include:      ["_pages"]
permalink:    /:title/

# About/contact
author:
  name:       José Del Valle
  url:        http://dlvx.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
sass:
  style: compressed